---
version: "3"

services:
  certs:
    build: .
    environment:
      - DOMAIN=example.org
    volumes:
      - ./default.conf:/web/default.conf
      - certs:/etc/letsencrypt
      - sites-availables:/sites-availables

volumes:
  certs:
    external: true
  sites-availables:
    external: true
