---
version: "3.5"

services:
  certs:
    image: anged/install_site
    environment:
      - DOMAIN=subdomain.example.org
      - EMAIL=admin@example.org
    volumes:
      - ./default.conf:/web/default.conf
      - certs:/etc/letsencrypt
      - sites-availables:/sites-availables
    networks:
      - selfhost

volumes:
  certs:
    external: true
  sites-availables:
    external: true

networks:
  selfhost:
    external: true
