---
version: "3.5"

services:
  install_site:
    build: path_to_repo
    restart: unless_stopped
    ports:
      - "80:80"
    environment:
      - BASE_URL=subdomain.domain.tld
      - EMAIL=admin@domain.tld
    volumes:
      - ./default.conf:/web/default.conf
      - sites-availables:/sites-availables
      - certs:/etc/letsencrypt

  app:
    build: path_to_app
    restart: always
    networks:
      - selfhost


volumes:
  sites-availables:
    external: true
  certs:
    external: true

networks:
  default:
  selfhost:
    external: true
