---
version: "3"

services:
  certs:
    image: anged/install_site
    environment:
      - DOMAIN=example.org
      - EMAIL=admin@example.org
    volumes:
      - ./default.conf:/web/default.conf
      - certs:/etc/letsencrypt
      - sites-availables:/sites-availables

volumes:
  certs:
    external: true
  sites-availables:
    external: true
