---
version: "3"

services:
  certs:
    build: .
    environment:
      - DOMAIN=example.org www.example.org
    volumes:
      - ./web_config:/web_config
      - certs:/etc/letsencrypt
      - nginx-conf:/sites-availables

volumes:
  certs:
    external: true
  nginx-conf:
    external: true
